import { Antenne, Mission } from './types';

export const ANTENNES: Antenne[] = [
  {
    id: 'croissy',
    nom: 'Croissy-Beaubourg',
    siege: true,
    adresse: '21 Rue des Veilles Vignes',
    ville: 'Croissy-Beaubourg',
    codePostal: '77183',
    tel: '01 60 05 XX XX',
    email: 'contact@secoursevangeliquedefrance.com',
    lat: 48.819716,
    lng: 2.643501,
    horaires: 'Lun–Ven 9h–17h',
  },
  {
    id: 'mureaux',
    nom: 'Les Mureaux',
    adresse: '2 Rue de la Motte',
    ville: 'Les Mureaux',
    codePostal: '78130',
    tel: '01 34 92 XX XX',
    email: 'mureaux@secoursevangeliquedefrance.com',
    lat: 48.995661,
    lng: 1.901535,
    horaires: 'Mar & Jeu 9h–16h',
  },
  {
    id: 'defense',
    nom: 'La Défense',
    adresse: '15 Esplanade de la Défense',
    ville: 'Puteaux',
    codePostal: '92800',
    tel: '01 47 76 XX XX',
    email: 'defense@secoursevangeliquedefrance.com',
    lat: 48.8924,
    lng: 2.2418,
    horaires: 'Lun–Ven 10h–18h',
  },
  {
    id: 'boissy',
    nom: 'Boissy-Saint-Léger',
    adresse: '8 Avenue Carnot',
    ville: 'Boissy-Saint-Léger',
    codePostal: '94470',
    email: 'boissy@secoursevangeliquedefrance.com',
    lat: 48.7514,
    lng: 2.5067,
    horaires: 'Mer & Ven 9h–15h',
  },
  {
    id: 'versailles',
    nom: 'Versailles',
    adresse: '23 Rue de la Paroisse',
    ville: 'Versailles',
    codePostal: '78000',
    tel: '01 39 50 XX XX',
    email: 'versailles@secoursevangeliquedefrance.com',
    lat: 48.8014,
    lng: 2.1301,
    horaires: 'Lun–Mer 9h–17h',
  },
  {
    id: 'gonesse',
    nom: 'Gonesse',
    adresse: '5 Rue Gabriel Péri',
    ville: 'Gonesse',
    codePostal: '95500',
    email: 'gonesse@secoursevangeliquedefrance.com',
    lat: 48.9873,
    lng: 2.4501,
    horaires: 'Mar & Jeu 10h–16h',
  },
  {
    id: 'chanteloup',
    nom: 'Chanteloup-les-Vignes',
    adresse: '1 Place de la Mairie',
    ville: 'Chanteloup-les-Vignes',
    codePostal: '78570',
    email: 'chanteloup@secoursevangeliquedefrance.com',
    lat: 48.9808,
    lng: 2.0392,
    horaires: 'Lun & Mer 9h–15h',
  },
  {
    id: 'viry',
    nom: 'Viry-Châtillon',
    adresse: '10 Rue des Écoles',
    ville: 'Viry-Châtillon',
    codePostal: '91170',
    email: 'viry@secoursevangeliquedefrance.com',
    lat: 48.6699,
    lng: 2.3705,
    horaires: 'Mer & Ven 9h–16h',
  },
  {
    id: 'creteil',
    nom: 'Créteil',
    adresse: '18 Allée du Vieux Pont',
    ville: 'Créteil',
    codePostal: '94000',
    tel: '01 48 99 XX XX',
    email: 'creteil@secoursevangeliquedefrance.com',
    lat: 48.7904,
    lng: 2.4553,
    horaires: 'Lun–Ven 9h–17h',
  },
  {
    id: 'orleans',
    nom: 'Orléans',
    adresse: '35 Rue de Bourgogne',
    ville: 'Orléans',
    codePostal: '45000',
    tel: '02 38 XX XX XX',
    email: 'orleans@secoursevangeliquedefrance.com',
    lat: 47.9029,
    lng: 1.9092,
    horaires: 'Mar & Jeu 9h–17h',
  },
  {
    id: 'massy',
    nom: 'Massy',
    adresse: '7 Allée de la Résistance',
    ville: 'Massy',
    codePostal: '91300',
    email: 'massy@sef-france.org',
    lat: 48.7308,
    lng: 2.2711,
    horaires: 'Lun & Mer 10h–16h',
  },
  {
    id: 'lemans',
    nom: 'Le Mans',
    adresse: '22 Rue de la République',
    ville: 'Le Mans',
    codePostal: '72000',
    tel: '02 43 XX XX XX',
    email: 'lemans@secoursevangeliquedefrance.com',
    lat: 47.9935,
    lng: 0.1990,
    horaires: 'Mar & Ven 9h–16h',
  },
  {
    id: 'compiegne',
    nom: 'Compiègne',
    adresse: '14 Rue Solferino',
    ville: 'Compiègne',
    codePostal: '60200',
    tel: '03 44 XX XX XX',
    email: 'compiegne@secoursevangeliquedefrance.com',
    lat: 49.4183,
    lng: 2.8258,
    horaires: 'Lun & Jeu 9h–15h',
  },
];

export const MISSIONS: Mission[] = [
  {
    id: 'jeunesse',
    titre: 'Jeunesse',
    description: 'Accompagnement des jeunes dans leur développement personnel, éducatif et social.',
    icon: '🌱',
    color: '#4BAE4F',
    bgColor: '#F0FBF0',
    actions: [
      'Soutien scolaire et tutorat',
      'Activités éducatives et culturelles',
      'Espaces jeunes et clubs',
      'Orientation et insertion professionnelle',
    ],
  },
  {
    id: 'sante',
    titre: 'Santé, Soins et Vie',
    description: 'Accès aux soins et accompagnement des personnes en situation de vulnérabilité médicale.',
    icon: '❤️',
    color: '#E8281E',
    bgColor: '#FFF0EF',
    actions: [
      'Accompagnement médico-social',
      'Aide aux soins de base',
      'Soutien aux personnes malades',
      'Prévention santé',
    ],
  },
  {
    id: 'education',
    titre: 'Réussite Éducative',
    description: 'Soutien aux familles pour favoriser la réussite scolaire et l\'épanouissement des enfants.',
    icon: '📚',
    color: '#2472C8',
    bgColor: '#EFF6FF',
    actions: [
      'Aide aux devoirs',
      'Soutien aux familles',
      'Accès à la culture et au sport',
      'Lutte contre le décrochage scolaire',
    ],
  },
  {
    id: 'famille',
    titre: 'Famille et Enfants',
    description: 'Protection et accompagnement des familles fragiles et des enfants en difficultés.',
    icon: '🏠',
    color: '#F5C518',
    bgColor: '#FFFBEF',
    actions: [
      'Accompagnement familial',
      'Protection de l\'enfance',
      'Soutien à la parentalité',
      'Médiation familiale',
    ],
  },
  {
    id: 'hebergement',
    titre: 'Hébergement & Logement',
    description: 'Aide à l\'accès et au maintien dans un logement digne pour les personnes sans-abri.',
    icon: '🏘️',
    color: '#8B38A2',
    bgColor: '#F8F0FB',
    actions: [
      'Hébergement d\'urgence',
      'Accompagnement vers le logement',
      'Aide aux démarches administratives',
      'Lutte contre l\'expulsion',
    ],
  },
  {
    id: 'alimentation',
    titre: 'NOUBES — Nourriture et Besoins Essentiels',
    description: 'Distribution alimentaire et aide aux besoins essentiels pour les familles démunies.',
    icon: '🛒',
    color: '#F05A28',
    bgColor: '#FFF3EE',
    actions: [
      'Épiceries solidaires',
      'Distribution de colis alimentaires',
      'Aide vestimentaire',
      'Accès aux produits d\'hygiène',
    ],
  },
  {
    id: 'insertion',
    titre: 'Réinsertion & Emploi',
    description: 'Accompagnement vers l\'emploi et soutien à l\'entrepreneuriat pour les personnes éloignées du marché du travail.',
    icon: '💼',
    color: '#29ABE2',
    bgColor: '#EEF9FF',
    actions: [
      'Aide à la recherche d\'emploi',
      'Formation et qualification',
      'Accompagnement des créateurs d\'entreprise',
      'Ateliers CV et entretiens',
    ],
  },
  {
    id: 'seniors',
    titre: 'Séniors et Retraités',
    description: 'Accompagnement des personnes âgées pour lutter contre l\'isolement et favoriser l\'autonomie.',
    icon: '🌟',
    color: '#4BAE4F',
    bgColor: '#F0FBF0',
    actions: [
      'Visites à domicile',
      'Accompagnement aux sorties',
      'Aide aux démarches numériques',
      'Activités inter-générationnelles',
    ],
  },
  {
    id: 'culture',
    titre: 'Culture, Art et Sport',
    description: 'Accès à la culture, aux arts et au sport pour tous, en particulier pour les publics défavorisés.',
    icon: '🎨',
    color: '#E8281E',
    bgColor: '#FFF0EF',
    actions: [
      'Ateliers artistiques',
      'Accès aux spectacles et musées',
      'Clubs sportifs solidaires',
      'Événements culturels communautaires',
    ],
  },
  {
    id: 'animation',
    titre: 'Animation des Territoires',
    description: 'Animation et développement du tissu associatif local dans les villes et les territoires.',
    icon: '🗺️',
    color: '#8B38A2',
    bgColor: '#F8F0FB',
    actions: [
      'Coordination des antennes locales',
      'Partenariats avec les collectivités',
      'Événements communautaires',
      'Développement territorial',
    ],
  },
];
